// This file is generated by vinext. Do not edit.
import type * as React from "react";

declare global {
  type PageProps<Route extends VinextRouteTypes.PageRoute = VinextRouteTypes.PageRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    searchParams: Promise<Record<string, string | string[] | undefined>>;
  };

  type LayoutProps<Route extends VinextRouteTypes.LayoutRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    children: React.ReactNode;
  } & {
    [K in VinextRouteTypes.LayoutSlotMap[Route]]: React.ReactNode;
  };

  type RouteContext<Route extends VinextRouteTypes.RouteHandlerRoute = VinextRouteTypes.RouteHandlerRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
  };
}

declare namespace VinextRouteTypes {
  type PageRoute = "/" | "/admin" | "/agendamentos" | "/agendar" | "/app" | "/cadastro" | "/clube" | "/entrar" | "/perfil" | "/planos" | "/privacidade" | "/termos";
  type LayoutRoute = "/";
  type RouteHandlerRoute = never;
  type AppRoute = "/" | "/admin" | "/agendamentos" | "/agendar" | "/app" | "/cadastro" | "/clube" | "/entrar" | "/perfil" | "/planos" | "/privacidade" | "/termos";

  interface ParamMap {
    "/": {};
    "/admin": {};
    "/agendamentos": {};
    "/agendar": {};
    "/app": {};
    "/cadastro": {};
    "/clube": {};
    "/entrar": {};
    "/perfil": {};
    "/planos": {};
    "/privacidade": {};
    "/termos": {};
  }

  interface LayoutSlotMap {
    "/": never;
  }
}



export {};
